build = "cargo +nightly build"
build-rel = "cargo +nightly build --release"
build-cli = "cargo +nightly build -p microagents-cli"
build-cli-rel = "cargo +nightly build -p microagents-cli --release"
clippy = "cargo +nightly clippy --all-targets"
clippy-fix = "cargo +nightly clippy --all-targets --fix --allow-dirty"
clippy-nodefault = "cargo +nightly clippy --no-default-features -p microagents-core"
clippy-fix-nodefault = "cargo +nightly clippy --fix --allow-dirty --no-default-features -p microagents-core"
format = "cargo +nightly fmt --all -- --check"
format-fix = "cargo +nightly fmt --all"
test = "cargo +nightly test"
build-nodefault = "cargo +nightly build --no-default-features -p microagents-core"
build-rel-nodefault = "cargo +nightly build --release --no-default-features -p microagents-core"
test-nodefault = "cargo +nightly test --no-default-features -p microagents-core"
